# Generated by Django 5.1.5 on 2025-01-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reading_period',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
